### ISSUE TITLE
Not able to install

### ISSUE THREAD

**Issue by cdevreugd** [okugami79/googletrend#6]
Hello,

Interesting package but I get the following error..

> install_github('googletrend','okugami79/googletrend')
> Downloading github repo okugami79/googletrend/googletrend@master
> Error in loadNamespace(name) : there is no package called ‘httr’
> In addition: Warning message:
> Username parameter is deprecated. Please use okugami79/googletrend/googletrend 
> install_github("okugami79/googletrend")
> Downloading github repo okugami79/googletrend@master
> Error in loadNamespace(name) : there is no package called ‘httr’
> install_github("okugami79/googletrend")
> Downloading github repo okugami79/googletrend@master
> Error in loadNamespace(name) : there is no package called ‘httr’
> install.packages("googletrend")
> Warning in install.packages :
>   package ‘googletrend’ is not available (for R version 3.2.0)

I hope someone can help!

Thanks in advance.

Cees

**Comment by cdevreugd** [comment]
Installing the httr package solved the problem.

**Comment by okugami79** [comment]
install.package('devtools')

ensure it is working.

On Thu, Apr 30, 2015 at 5:38 AM, cdevreugd notifications@github.com wrote:

> Hello,
> 
> Interesting package but I get the following error..
> 
> install_github('googletrend','okugami79/googletrend')
> Downloading github repo okugami79/googletrend/googletrend@master
> Error in loadNamespace(name) : there is no package called 'httr'
> In addition: Warning message:
> Username parameter is deprecated. Please use
> okugami79/googletrend/googletrend
> install_github("okugami79/googletrend")
> Downloading github repo okugami79/googletrend@master
> Error in loadNamespace(name) : there is no package called 'httr'
> install_github("okugami79/googletrend")
> Downloading github repo okugami79/googletrend@master
> Error in loadNamespace(name) : there is no package called 'httr'
> install.packages("googletrend")
> Warning in install.packages :
> package 'googletrend' is not available (for R version 3.2.0)
> 
> I hope someone can help!
> 
> Thanks in advance.
> 
> Cees
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/okugami79/googletrend/issues/6.

## 

Best & Cheers

Chris

**Comment by cdevreugd** [comment]
Dear Chris,

Thanks for your answer. The Devtools package works but I get the following
error:

  package ‘googletrend’ is not available (for R version 3.2.0)

I hope you can help!

Best regards and thanks  in advance!

Cees

Op ma 11 mei 2015 om 01:11 schreef Chris Okugami notifications@github.com:
